version: '3'

services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - db-dev
    networks:
      - db
      - external
    volumes:
      - ${PWD}/pgadmin-data/:/var/lib/pgadmin/

networks: 
  db:
  external:
    external: true

